### ISSUE TITLE
ssl-skip-validation not working

### ISSUE THREAD

**Issue by chavezom** [drone-plugins/drone-cloudfoundry#8]
ssl-skip-validation is not recognized.

With the following build yaml I am getting the below error:

YAML:
deploy:
  cloudfoundry:
    api: api.xx.xxx.xxx.xxx.xip.io
    user: $$USER_NAME
    password: $$USER_PASSWORD
    org: the-org
    space: pro
    when:
      branch: master
    skip-ssl-validation: true

ERROR:
[info] Pulling image plugins/drone-cloudfoundry:latest
Drone Cloud Foundry Plugin built at 2016-02-02 08:47:30 UTC
Setting api endpoint to api.15.209.123.150.xip.io...
FAILED
Invalid SSL Cert for api.15.209.123.150.xip.io
TIP: Use 'cf api --skip-ssl-validation' to continue with an insecure API endpoint
[info] build failed (exit code 1)

**Comment by chavezom** [comment]
I submitted a pull request to fix this, waiting to see the change on the docker image.

**Comment by viniciusffj** [comment]
Any update on that?
I'm having this issue also
